version: '3.7'
services:
    postgres:
        image: postgres:9.6
        container_name: postgres-db
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
    mysql:
        image: mysql
        container_name: mysql-db
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306









