version: '3.7'
services:
    database:
        image: postgres:9.6
        container_name: postgres-db
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"







